const ENV = 'ENV';
const DB_TYPE = 'DB_TYPE';
const DB_HOST = 'DB_HOST';
const DB_PORT = 'DB_PORT';
const DB_USER = 'DB_USER';
const DB_PASS = 'DB_PASS';
const DB_NAME = 'DB_NAME';
const HASH_ROUNDS = 'HASH_ROUNDS';
const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';

export const ENV_KEY = {
  ENV,
  DB_TYPE,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASS,
  DB_NAME,
  HASH_ROUNDS,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
};
